### ISSUE TITLE
ankilink from mindmanager not working

### ISSUE THREAD

**Issue by ccchan234** [napretep/hjp-bilink#3]
![image](https://user-images.githubusercontent.com/37549409/234019087-5c0a79ab-7405-453e-bf03-ad97d3de1227.png)

i have ran the portable anki /w admin rights, even for this time.

also running the mindmanager /w admin rights.

after clicking,
nothing happens.

**Comment by ccchan234** [comment]
nothing happen also from obsidian
![image](https://user-images.githubusercontent.com/37549409/234020424-fc791187-1119-4999-86ce-1ceb3d3cfe48.png)

**Comment by ccchan234** [comment]
![image](https://user-images.githubusercontent.com/37549409/234021619-cf954388-3200-4721-93ad-041c445fbf09.png)

even the card is copied as html, and pasted into the other card, it's not working.

may be it's not compatible /w some other addons.

**Comment by napretep** [comment]
this problem is from your system. your system do not give you the admin right, so the addon cannot register the ankilink protocol to open card outside anki.

**Comment by ccchan234** [comment]
> this problem is from your system. your system do not give you the admin right, so the addon cannot register the ankilink protocol to open card outside anki.
hi,

i guess this plugin is not compatible with the portable version of anki, as above.


i then installed the INSTALL version of anki, it works! thanks.
