### ISSUE TITLE
just ask, can i use this addon in offline machines? thx

### ISSUE THREAD

**Issue by ccchan234** [napretep/hjp-bilink#4]
hi,

because of political reasons, i may turn my windows into airgap-ed, no internet windows 10.

can this addon still function?

as i read that the addon have a web ver or local ver of something?

thanks

**Comment by napretep** [comment]
"版本号以l结尾表示插件从本地磁盘安装,以w结尾则表示插件是在插件管理窗口中输入插件代码后从ankiweb下载安装, 有的人会同时安装这两者, 这样会导致一些错误, 所以我增加了识别功能, 如果发现同时安装了本地版和网络版,则会自动屏蔽本地版,仅启用网络版. 你离线使用anki与你装哪个版本都无关"   
"The version number ending with 'l' indicates that the addon is installed from the local disk, while the one ending with 'w' indicates that the addon is downloaded and installed from AnkiWeb after entering the addon code in the addon management window. Some people may install both, which can cause some errors. Therefore, I have added recognition functionality that automatically disables the local version and only enables the web version if both are detected. The version you install has no impact on your offline use of Anki."
