### ISSUE TITLE
[FR] keep ankilink:// protocol alive, my thinking of simplified use and wish to donate. thx

### ISSUE THREAD

**Issue by ccchan234** [napretep/hjp-bilink#5]
1. hi, the ankilink:// URL protocol is the most important one, please keep it live forever! although it only work in windows, and need install version of anki
2. i feed every bit of info into mindmaps e.g. mindmanager; now every node of mindmap can use ankilink to link to an anki card; and from each anki card, i can use mj-map:// to link to any node of mindmap. indeed after you do an anki card, u can use the mj-map link to go to mindmap, and see the whole picture and if you wish, you can easily "go to " other anki cards thru the ankilinks.
![image](https://user-images.githubusercontent.com/37549409/235305560-d2d423ec-e9a4-41d4-baed-8a54b1d6ed64.png)

3. i saw alipayCN/wechatCN QR code for donation. i just wish to donate 2USD. are the codes still update and useable? thanks

**Comment by ccchan234** [comment]
ps: for the above graph, left hand side is ANKI, right hand side is mindmanager mindmap.

**Comment by ccchan234** [comment]
ps: you can use onenote instead of the mindmap, just use anything that you could "hyperlink directly to the paragraph"

**Comment by napretep** [comment]
"感谢你的支持, 我没有境外账户,  如果你方便的话, 你可以试试能否通过那两个二维码捐赠. 我会尽量维护ankilink协议功能, 不过他是一个次要功能, 我主要的精力用在视图模式上" 
"Thank you for your support. I don't have an overseas account. If it's convenient for you, you can try to donate through those two QR codes. I will do my best to maintain the AnkiLink protocol functionality, but it is a secondary feature, and my main focus is on the view mode."

**Comment by ccchan234** [comment]
> 

hi, where is that 2 QR code? thank you.
sometimes the links to documents work, sometimes not.
i'll try to find it. i got wechatpay CN. thx

**Comment by ccchan234** [comment]
@napretep hi, 
1. the notion link is dead. (not important i think)
2. i just came over the 2 QR codes once, now i cant find them even i searched hard. pls provide again if possible, thanks.

**Comment by napretep** [comment]
![weixinpay](https://user-images.githubusercontent.com/7680792/235339411-0a067cf7-9d92-44ba-aab9-f94683691dd8.jpg)
![alipay](https://user-images.githubusercontent.com/7680792/235339412-ce314b6e-3174-41b7-b641-487bf0d13d04.jpg)

**Comment by ccchan234** [comment]
> ![weixinpay](https://user-images.githubusercontent.com/7680792/235339411-0a067cf7-9d92-44ba-aab9-f94683691dd8.jpg) ![alipay](https://user-images.githubusercontent.com/7680792/235339412-ce314b6e-3174-41b7-b641-487bf0d13d04.jpg)

just sent half cup of coffee, thx for your software.
i'll close this issue too.

thanks
