### ISSUE TITLE
will hjp bilink work/be updated for anki 23.10.x?

### ISSUE THREAD

**Issue by ccchan234** [napretep/hjp-bilink#7]
anki 23.10, with ankidroid 2.17(not yet officially out) will use Yip's FSRS algorithm.

looks like everyone want to use it.

i haven't tried because i will wait for ankidroid 2.17 (now 2.16).

any info on this?

thanks

**Comment by napretep** [comment]
Hello, I have been focused on preparing my PhD applications over the past year, which has left me without much time for plugin development. The earliest I anticipate being able to resume development work is spring or summer of next year. Optimistically, if my PhD applications are successful by January, I could potentially start on plugin development again at that time.
你好, 我最近一年在准备我的博士申请工作, 没有时间开发插件, 最迟预计明年春天或夏天才会有时间继续开发,乐观的话等明年一月份通过博士申请就可以开始开发了.

**Comment by inww7** [comment]
+1

**Comment by ccchan234** [comment]
> Hello, I have been focused on preparing my PhD applications over the past year, which has left me without much time for plugin development. The earliest I anticipate being able to resume development work is spring or summer of next year. Optimistically, if my PhD applications are successful by January, I could potentially start on plugin development again at that time. 你好, 我最近一年在准备我的博士申请工作, 没有时间开发插件, 最迟预计明年春天或夏天才会有时间继续开发,乐观的话等明年一月份通过博士申请就可以开始开发了.

不打緊,
我明年中之前也是考試,
估計暫時也是不會上23.10.

不過我試過在23.10 試用,
23.10 就表明 hjp bilink 行不了, 要更新.
我也是資料提供一下吧了.

祝大家安康, 中華威武!

"It doesn't matter,
I also have exams before the middle of next year,
I guess I won't be on 23.10 for the time being.

However, I have tried using 23.10,
23.10 clearly indicates that hjp bilink doesn't work, it needs to be updated.
I might as well provide the information.

I wish everyone well-being, mighty China!"
(translated using gpt4)

**Comment by ccchan234** [comment]
btw, ankilink:// 這個功能最重要, 其他的view 其實可以用mindmanager 或其他 軟件代替.
如果只做最重要的, 我建議集中做這個功能,
或許看看會不會分拆開兩個addon? thanks

"btw, the ankilink:// feature is the most important, other views can actually be replaced by MindManager or other software. If only focusing on the most important, I suggest concentrating on this feature. Perhaps consider whether to split it into two separate add-ons? Thanks"

**Comment by ccchan234** [comment]
我見2024年1月更新了，
讓我試試看.
let me try the 2024 jan update.
